### ISSUE TITLE
Support other units than nm for dataset voxel size

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos-libs#1076]
WEBKNOSSOS now supports unit-aware voxel sizes as of https://github.com/scalableminds/webknossos/pull/7783

- The libs should also understand datasource jsons in this format, but the old ones too (default to nm)
- It should be possible to specify the unit during dataset creation
- The libs API client should use HTTP API version 7

**Comment by hotzenklotz** [comment]
What happens when uploading a new dataset through the WK web UI when I specify a voxel size in, e.g. cm? Is this info passed to the worker as centimeters or converted to be backward compatible?

**Comment by fm3** [comment]
@MichaelBuessemeyer maybe you could have a look at this? I believe the frontend sets the parameters for the conversion job? Should be converted to nm for the moment I guess.

**Comment by fm3** [comment]
Thanks for investigating. I’ll add an adapter to the backend code so that it will convert the unit to nanometer for now, before passing it to the worker job parameters.

Adapting the worker to actually use the unit requires this libs issue to be solved first, which will probably take a bit of time.

**Comment by fm3** [comment]
Done that in https://github.com/scalableminds/webknossos/pull/7783/commits/d3410be3ebad5affaf5d6911c4130c7914a5f286 :) Good catch!
