### ISSUE TITLE
Margin padding fails for layer bounding boxes

### ISSUE THREAD

**Issue by AndreaNathansen** [scalableminds/webknossos-libs#1117]
## Context
- I tried to add padding to a layer bounding box as e.g. in [this voxelytics script](https://github.com/scalableminds/voxelytics/blob/a5c4187b8858f2fddc0f7a8cf18f64c81bbd6e69/voxelytics/connect/tools/convert_segmentation_layers_to_one_annotation.py#L68).

## Expected Behavior
- The padded bounding box should be returned.

## Current Behavior
- Currently, I get a `NotImplementedError` because the layer bounding box is an NDBoundingBox for which `padded_with_margins` has not been implemented yet.

## Steps to Reproduce the bug
1. Load a Dataset, get one of the layers' bounding box.
2. Try to add padding by calling `padded_with_margins` on the bounding box.

**Comment by fm3** [comment]
Note that if you know your layer to be 3D only, you can use the adapter `wk.BoundingBox.from_ndbbox(layer.bounding_box)`
