### ISSUE TITLE
Add max_mag to webknossos convert

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-libs#1202]
## Detailed Description
Add an optional `--max-mag` argument to the `webknossos convert` and `webknossos downsample` CLIs.

## Use Cases & Context
Sometimes, users just don't want to downsample so deep.

**Comment by markbader** [comment]
Two questions about implementation:
- I would suggest using --coarsest-mag instead of --max-mag to make the naming consistent.
- `webknossos convert` does not downsample yet. Should it downsample the created Dataset, or should it stay as it is?

**Comment by normanrz** [comment]
> I would suggest using --coarsest-mag instead of --max-mag to make the naming consistent.

That's good.

> webknossos convert does not downsample yet. Should it downsample the created Dataset, or should it stay as it is?

I thought it does downsampling, but ok. Let's not change this right now.
