### ISSUE TITLE
Ensure that tests cover cases with > 32 slices

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos-libs#125]

**Comment by jstriebel** [comment]
@philippotto Do you remember what this was about? Is this especially for wkcuber conversion jobs? Please add some more description.

**Comment by philippotto** [comment]
I think, this was about making sure that test cases which cause code to write WKW data should ideally write more than 32 data slices, since a lower slice count is not really representative (and might not catch bugs since the use case is too simple). However, the issue is quite old and I don't feel like it's really essential/relevant, right now. Therefore, I'm closing it, but feel free to reopen.
