### ISSUE TITLE
NIFTI write missing layers

### ISSUE THREAD

**Issue by leowe** [scalableminds/webknossos-libs#213]
If specified segmentation or color layers are missing, there should be an option to simply write empty wkw files instead

**Comment by leowe** [comment]
Good question. I can't remember 100% what this referred to. I imagine it was when converting a whole folder / many datasets of NIFTI files to wkw that when a specific file was missing (e.g. the specified NIFTI file for a layer like the segmentation) the execution stopped or didn't write anything. Afterwards I probably had to go over and check which files were missing and create empty layers for them and add them to the `datasource-properties.json`.

I think that this is probably not a big use case and if it can't be done cleanly, it doesn't have to be done at all. The dataset API is much better now, 2 years ago this was a much bigger issue.

**Comment by jstriebel** [comment]
Ok, I'll close it then for now, please re-open if this is a problem again :+1:
