### ISSUE TITLE
Support Python 3.10

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos-libs#257]
Looks like Python 3.9 does not yet work with `wkcuber`. 

https://github.com/scalableminds/webknossos-cuber/runs/1571097340?check_suite_focus=true

**Comment by erjel** [comment]
It also does not work with `webknossos`. With Python 3.9 I get:
```
TypeError: Invalid first argument to `register()`. typing.Literal['color', 'segmentation'] is not a class.
```
for a simple:
```python
import webknossos as wk
```
Please restrict the PyPi dependencies accordingly or run unit test also against 3.9 & 3.10. False badges in `README.md` do not help anyone ...

**Comment by hotzenklotz** [comment]
Thanks for letting us know. 

> Please restrict the PyPi dependencies accordingly or run unit test also against 3.9 & 3.10. False badges in README.md do not help anyone ...

That's unfortunate. This are inferred automatically from the `pyproject.toml`. It seems newer versions are underspecified there. Will fix that.

**Comment by jstriebel** [comment]
wk-libs supports Python 3.9 in the meantime, and the badges in the Readme are fixed. Python 3.10 is not tested yet and might not work.
