### ISSUE TITLE
Support 2d conversion 

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-libs#272]
The wkw format is ill-suited for large 2D images. Therefore, webknossos has experimental support for tiled-tiff formats. The cuber should auto-detect 2D input files and convert them to tiled-tiffs including metadata.

I believe @fm3 has some example code for how to produce tiled tiffs.

**Comment by fm3** [comment]
See https://github.com/scalableminds/webknossos-connect/pull/97

**Comment by fm3** [comment]
The zarr adapter in the wk backend supports 2d chunk sizes. However, the backend logic is not really optimized for these. It will still do 32³ cutouts etc

**Comment by jstriebel** [comment]
Thanks for the info! Then we could still do 2D chunk sizes, at it would greatly reduce the storage on disk / in the cloud. Efficiency for streaming this to the browser is a different topic I think.

**Comment by markbader** [comment]
This issue is outdated as the preferred solution are zarr datasets now. The default chunk shape for zarr-datasets is set to a 2D shape if the input image is 2D.
