### ISSUE TITLE
Support ND2 files

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-libs#273]
ND2 is a format from Nikon and is supported through the `nd2reader` package. ND2 is often used for fluorescence light microscopy (maybe multiple layers).

Sample code:
```
from nd2reader import ND2Reader

a = ND2Reader(input_path)
size = a.metadata['pixel_microns'] * 1000
a = np.stack(a).T
print(a.shape, a.dtype)
```

**Comment by jstriebel** [comment]
This is already supported via the pims bioformats reader in `Dataset.from_images()`, see also #826 and #825. Closing therefore.
