### ISSUE TITLE
Align conversion interfaces

### ISSUE THREAD

**Issue by youri-k** [scalableminds/webknossos-libs#281]
Currently, the image stack conversion contains downsampling and compression, while the knossos and nifti conversion do not contain them. This should be changed, so that all `convert_x` entry points include the downsampling and compression by default.
Additionally, the readme could be adapted to clearly show the difference between the larger features, e.g. conversions, and helper functions, e.g. equality checking.

**Comment by jstriebel** [comment]
Since those interfaces will be replaced by `Dataset.from_images()` as of #825, this is obsolete.
