### ISSUE TITLE
Investigate non-API uses of wkcuber

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-libs#325]
I think we should move all downstream usages of wkcuber to the `wkcuber.api` API instead of imports to the CLI modules.
As a first step, it would be good to know what functions of wkcuber are used in our other projects (voxelytics, wk-worker, wk-connect) and how much effort it would be to migrate those. While doing that, it would also be interesting to know, whether the low-level `wkw` lib is used in one of these projects.

**Comment by jstriebel** [comment]
@rschwanhold Could you re-check what parts are missing and create smaller issues for coherent packages? Thanks :pray:

**Comment by jstriebel** [comment]
superseded by #188
