### ISSUE TITLE
dataset api: read should return 3D array for single-channel layers

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos-libs#351]
A typical use case is to have a segmentation or grey-scale layer, which only has a single layer. Reading on this layer produces an array with 4 dimensions and a shape of `(0, width, height, depth)`. I'd find this confusing for "simple" use-cases and expect a 3D array instead for such layers. To be able to have a "standardized" interface, I'd propose to add a `always_include_channels` flag with a `False` default to `view.read`, which allows to always output a 4D array (e.g. for wrapper methods which might not want to have special cases for 3D and 4D arrays).

PS: `view.write` handles both 3D and 4D arrays.

**Comment by jstriebel** [comment]
@normanrz @philippotto What's your opinion on this?

**Comment by philippotto** [comment]
yes, sounds good to me :+1: I agree, that it can be confusing which is especially a bummer when the use case is "simple". keeping consistency via an optional parameter seems like a good trade-off :+1:

**Comment by jstriebel** [comment]
@normanrz You mentioned that you'd rather stick to 4d array now, but reacted differently previously. Any strong opinions? I think that removing the channels dimension is fine for arrays without channels, but don't care too much about it.

**Comment by normanrz** [comment]
I think it is not an easy trade-off. I would tilt towards to keeping the behavior as is.

**Comment by jstriebel** [comment]
Closing this for now, we might re-evaluate this for another major version if this comes up, but probably not changing this for v1/2.
