### ISSUE TITLE
[wk-lib] polish & publish common documentation

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos-libs#379]
We want to have a common documentation for all libs in the wk-libs repository, which is published. This should consist both of guides/tutorials/… as well as API-documentation.

Therefore we should add doc-generation top-level and include all sub-packages there. A proposal for the stack, which is similar to our vx stack:
* [mkdocs](https://www.mkdocs.org) for guides etc and to integrate the API docs
* [Material Design Theme](https://squidfunk.github.io/mkdocs-material/)
* API docs either via
  * [pdoc](https://pdoc.dev) for API docs, see this [example for mkdocs integration](https://github.com/mitmproxy/pdoc/tree/main/examples/mkdocs), or
  * [mkdocstrings](https://github.com/mkdocstrings/mkdocstrings)
  * more options are available: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#api-documentation-building
 * Useful mkdocs extensions:
   * https://facelessuser.github.io/pymdown-extensions
* Nice example setup: https://github.com/ezsystems/developer-documentation/blob/master/mkdocs.yml
* For publishing we can either use S3, or github pages

**Comment by normanrz** [comment]
#392 publishes the current docs to S3

**Comment by jstriebel** [comment]
Most of the setup will be done with #420, but further work will be needed, e.g.
* Show examples prominently
* Specific guides and tutorials
* Version selection (see https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning & https://github.com/squidfunk/mkdocs-material-example-versioning/tree/gh-pages)
