### ISSUE TITLE
Document command line parameters

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos-libs#39]
From a quick look, not all command line parameters are documented, some of them fairly important, for example `--max` to specify the maximum down-sampled resolution, or the different interpolation modes. Either, extend the usage examples to include all parameters or better add a section where all of them are explained briefly.

**Comment by normanrz** [comment]
Would be great if we could generate that from the code. You can always run without args to get the usage printed.

**Comment by jstriebel** [comment]
Might get fixed via #825

**Comment by hotzenklotz** [comment]
The switch to `typer` should cover most of this. It automatically will print all the parameters with `--help` etc
