### ISSUE TITLE
Fix permission/ownership of created data when using docker

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos-libs#40]
When using docker to run the cuber, the created data directories and files are root-owned, which is not ideal and creates problems when further processing the data or importing it into wK.
Ideally, the files should belong to the user that executes the cubing script. @jstriebel mentioned this could be achieved by wrapping the docker command in a small script to correctly set the UID/GID. Imo, it would be even better if we could achieve this without the need to have this extra script, so a user can simply copy the command and execute it.

**Comment by normanrz** [comment]
Basically you need to add `-u $(id -u):$(id -g)` to the docker run command. Either in the readme or in a script. There is no intrinsic way to do this.

**Comment by daniel-wer** [comment]
No longer relevant, closing
