### ISSUE TITLE
[client] Parallelize dataset download

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos-libs#466]
Currently, the generated client uses a fresh httpx client for every request (see also issue https://github.com/openapi-generators/openapi-python-client/issues/202 about this), and the resumable-client currently also for one session (but accepts a client in the constructor). This client should also add a global [response event hook (see the `raise_on_4xx_5xx` example)](https://www.python-httpx.org/advanced/#event-hooks) for failed requests. Additionally, the api should use parallel requests where possible e.g. via async-routines.

**Comment by motybz** [comment]
I vote for this feature since it will make a significant performance improvement on multiple calls.
Any plan to implement it?

**Comment by jstriebel** [comment]
@motybz Sorry for the late reply, this is definitely on our radar! Atm we're focusing on a stable API, but we'll tackle this afterwards to improve up- & download speed.

**Comment by Olian04** [comment]
@jstriebel what's the status on this issue? Any updates in the past nine months?

**Comment by jstriebel** [comment]
@Olian04 So far there was little progress, as this is mostly blocked by https://github.com/openapi-generators/openapi-python-client/issues/202.

The following points can be tackled independently already, we'll try to tackle those soonish:
* [ ] Register a global httpx Client
* [ ] Use this client where httpx is used directly:
  * dataset upload
  * task creation
  * annotation upload
* [ ] Add useful middle ware, such as good error handling and token-reloading
* [ ] Use async methods to schedule requests in parallel where possible (mostly dataset download)

**Comment by dbanty** [comment]
Hey @jstriebel, I'm just going over mentions of the openapi-python-client issue to find folks to review https://github.com/openapi-generators/openapi-python-client/pull/775 before it merges (since it's a breaking change). I'd love your input!

**Comment by philippotto** [comment]
A short update: @fm3 pushed 00e168323a0ac7d47d17edf209ac0d8a340f3b34 last week which removes the auto-generated client. As a byproduct, allocating a fresh httpx client for each api call is not done, anymore. Parallelizing the download of a dataset is still an open point.

**Comment by normanrz** [comment]
The `webknossos` package now uses [zarrita](https://github.com/scalableminds/zarrita) under the hood which uses async io to fetch chunks concurrently.
