### ISSUE TITLE
Persist log file

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos-libs#478]
When running the cuber, there usually is a lot of output (overflowing terminal buffers). It would be great if all of that output would be persisted in a log file as well to allow to easily scan and search through it, afterwards.

**Comment by philippotto** [comment]
Do you have an opinion about where the log file should be placed? Something like `./logs/cuber_{timestamp}.txt` ?

**Comment by daniel-wer** [comment]
Sounds good to me :)
