### ISSUE TITLE
Create BoundingBoxFloat and Vec3Float classes

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos-libs#483]
BoundingBox and Vec3Int are currently limited to integers. For many use cases, this is the desired behavior, but there are also use cases where a float bounding box (e.g. in nm-space) would be useful.

**Comment by markbader** [comment]
@fm3 are these float Bounding Boxes still needed for some use cases? As we introduced the unit parameter of the voxel size, I would argue that smaller spaces can be represented by using a smaller unit.

**Comment by fm3** [comment]
It’s about calculations with real-world coordinates (not on the voxel level, but on, say, the nm level). There, int is a restriction. We might want to divide different values and be interested in float accuracy. That said, I’m not sure if the libs need to support this. I haven’t been using them that much lately. Maybe @valentin-pinkau can comment

**Comment by valentin-pinkau** [comment]
In voxelytics I don't see a need for a BoundingBoxFloat
