### ISSUE TITLE
In webknossos client, during dataset upload, avoid zip file creation

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos-libs#501]
Creating the zip file on the client can take a long time. On the server it is unpacked again, which can again take a long time and will create load on the server. Instead, the files should be sent individually. Since WKW will usually create 1GB-Files, this should not be too much overhead. The webknossos backend (and js frontend) already support both.

**Comment by normanrz** [comment]
This would be great. Does the resumability also work with the individual files?

**Comment by fm3** [comment]
Yes, only the python client needs to be adapted.

**Comment by jstriebel** [comment]
Ah, good to now :+1: This might (:tm:) be as easy as
* adapting `totalFileCount`
* calling `add_file` multiple times
* adapting the progress-bar counts

https://github.com/scalableminds/webknossos-libs/blob/master/webknossos/webknossos/client/_upload_dataset.py#L58-L76
