### ISSUE TITLE
Add `Progress` to wkcuber tasks as well

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-libs#513]
The progress bar for dataset upload is very nice. It would be great to have that for the tasks in wkcuber as well.

**Comment by rschwanhold** [comment]
Related to Issue #366

**Comment by rschwanhold** [comment]
Currently, tasks like `downsampling` log much information. Should this be completely removed? I assume that this information could be helpful if there is some error.

Example output:
```
2021-12-09 13:38:42,199 INFO Cubing z=0-8
2021-12-09 13:38:42,200 INFO Cubing z=32-40
2021-12-09 13:38:42,284 DEBUG Cubing of z=0-8 took 0.08500051s
2021-12-09 13:38:42,284 DEBUG Cubing of z=32-40 took 0.08399725s
```

**Comment by normanrz** [comment]
I think a lot of the output is just there, because there isn't a better visualization that shows a) progress and b) ETA. The messages shown today, could be still displayed when using a `--verbose` flag or something.
