### ISSUE TITLE
Add MagView.get_views_on_disk

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-libs#532]
[MagView.get_bounding_boxes_on_disk](https://docs.webknossos.org/api/webknossos/dataset/mag_view.html#MagView.get_bounding_boxes_on_disk) is very useful. However, there may be some confusion, because it returns global offsets, even when the `MagView` has its own offset. It would be great to add a new method that returns `View`s directly.

Also, `MagView.get_bounding_boxes_on_disk` doesn't return bboxes but `(offset, size)` pairs.

**Comment by jstriebel** [comment]
The method now returns bounding boxes and using global offsets is more staight forward. A small wrapper returning views would still be useful :+1:
