### ISSUE TITLE
cluster_tools slurm timeout issue

### ISSUE THREAD

**Issue by elhuhdron** [scalableminds/webknossos-libs#537]
Thank you for implementing the new features that query for `MaxArraySize` and `MaxSubmitJobs` in slurm. Unfortunately, on our system I am still having an issue. On our system `MaxSubmitJobs` is not defined (allows for unlimited queued jobs), however, after 9 rounds of array job submissions (each 1001 in size), slurm responds to the next submission with a timeout-type error:

```
2021-12-22 23:15:23,214 DEBUG Number of currently submitted jobs is 9053.
Exception in thread Thread-13452:
Traceback (most recent call last):
  File "/gpfs/soma_fs/home/watkins/anaconda3/envs/wkw-new/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/gpfs/soma_fs/home/watkins/anaconda3/envs/wkw-new/lib/python3.8/site-packages/cluster_tools/schedulers/slurm.py", line 337, in run
    job_id = SlurmExecutor.submit_text(script, self.cfut_dir)
  File "/gpfs/soma_fs/home/watkins/anaconda3/envs/wkw-new/lib/python3.8/site-packages/cluster_tools/schedulers/slurm.py", line 154, in submit_text
    job_id, stderr = chcall("sbatch --parsable {}".format(filename))
  File "/gpfs/soma_fs/home/watkins/anaconda3/envs/wkw-new/lib/python3.8/site-packages/cluster_tools/util.py", line 65, in chcall
    raise CommandError(command, code, stderr)
cluster_tools.util.CommandError: 'sbatch --parsable .cfut/_temp_slurm9LFK0819HxEcazy2sTtbM72vFlHDuUlX.sh' exited with status 1: b'sbatch: error: Slurm temporarily unable to accept job, sleeping and retrying\nsbatch: error: Batch job submission failed: Resource temporarily unavailable\n'
```

I'm not sure how easily reproducible this is, particularly if you are testing with a docker instance. Although I like the automatic query, would it be possible to add manual control of these, so they can be specified as part of the job resources (i.e., how large of array size jobs to submit and how many can be submitted/running at once)? This would be an easy workaround.

**Comment by elhuhdron** [comment]
I opened pull request #538 as a potential suggestion for the workaround. For me this resolved the issue, as I can specify a maxsubmit value below 8000 (I used 3000) and my cubing jobs completed.

**Comment by daniel-wer** [comment]
Hi @elhuhdron, thank you for the detailed report.

Usually, this kind of error indicates that Slurm's `MaxJobCount` is configured too low, which is the maximum number of jobs Slurm can have in its active database (across all users). If it is not configured, the default is 10,000 which seems to be consistent with what you're describing.
My recommendation would be to increase `MaxJobCount` and set `MaxSubmitJobsPerUser` to be a fraction of `MaxJobCount` to avoid running into this issue in the future without any extra per-job configuration needed.

Still, I can see that it might be helpful to have an override for these values. Thank you for submitting a PR in that regard. I'll have a look and think about a good solution for that.

**Comment by elhuhdron** [comment]
Hi @daniel-wer,
Yes, you are correct, it seems that these values on our system have been left at their presumable defaults:

```
scontrol show config | grep -E 'MaxArraySize|MaxJobCount'
MaxArraySize            = 1001
MaxJobCount             = 10000
```

Thank you for pointing that out and I will indeed ask our administrators about it.
However, as you say, I would still prefer to allow the user the option to control these, as in addition to working around whatever the hard slurm configuration constraints are, it allows for more flexibility for the user to manage their jobs. For users that do not care, it could then still default to the automatic querying.
