### ISSUE TITLE
[wkcuber] cleanup testing

### ISSUE THREAD

**Issue by jstriebel** [scalableminds/webknossos-libs#580]
Currently the test setup consists of different scripts as well as pytest tests. The following commands are run in CI:
```bash
tar -xzvf testdata/WT1_wkw.tar.gz
poetry run pytest tests
poetry run tests/scripts/all_tests.sh
```

There's also a `test.sh` which is outdated atm. We should ensure that this script works, is used in CI and reflects all tests needed and expected. Additionally, we might double-check some of the scripts, they might also be refactored to pytest tests.

Related: #409

**Comment by jstriebel** [comment]
PS: http://docs.webknossos.org/webknossos-py/development.html#wkcuber-package should be updated accordingly

**Comment by philippotto** [comment]
> Additionally, we might double-check some of the scripts, they might also be refactored to pytest tests.

Yes, I think, this would make a lot of sense. Could be done peu à peu. Also see
https://github.com/scalableminds/webknossos-libs/pull/657/files#r829123141
