### ISSUE TITLE
Comments from point-of-view of first-time user

### ISSUE THREAD

**Issue by amotta** [scalableminds/webknossos-libs#594]
Yesterday, while trying the webknossos Python library for the first time, I've encountered the following difficulties:

1. Initially, I did not find the documentation. I had assumed that the documentation would be linked from the "webKnossos Python API" section of the README. Only quite a bit later did I find the link in the right-hand column ("About") and the tiny green button at the top of the README.
2. The difference between an `Annotation` and a `Skeleton` is still not entirely clear to me. (In case of a hybrid tracing, an `Annotation` can contain more than a `Skeleton`, I guess.) At first, I've tried `webknossos.Annotation.load('/path/to/tracing.nml').skeleton()`. This currently raises the following error: "zipfile.BadZipFile: File is not a zip file".

Strictly speaking, these are not bugs. So, feel free to close the issue without comment.

**Comment by jstriebel** [comment]
We just published release `0.9.9` which includes some new features and fixes for skeletons and annotations. Annotations can now also be loaded from and saved as `.nml` if they are skeleton-only, as well as down- and uploaded. I also polished the Annotation docs a bit, please let us know if this is still confusing or where it needs improvements:
https://docs.webknossos.org/api/webknossos/annotation/annotation.html

Again, thanks a lot for the feedback, happy to hear that you're trying out the libs :rocket: Closing this issue for now, feel free to re-open.
