### ISSUE TITLE
Add a feature to list all uploaded datasets

### ISSUE THREAD

**Issue by filippocastelli** [scalableminds/webknossos-libs#628]
It would be nice to have a simple API call to list all available datasets.
At the moment I use the `/datasets` API endpoint and it works well, but it would be a nice feature to add to the `webknossos` python package.

```python
import requests
import pandas as pd

session = requests.session()
headers = {"X-Auth-Token": <webknossos_API_token>}
base_url = "http://webknossos/api"
resp = session.get(base_url + "/datasets", headers=headers)
df = pd.DataFrame(resp.json())
df = df[df.owningOrganization == <organization_id>]

```

**Comment by hotzenklotz** [comment]
Thanks for the suggestion. Could you elaborate a bit? What would be your use case for that?

**Comment by filippocastelli** [comment]
Thank you for the instant reply.
I'm automating the upload of multiple datasets, before uploading I want to make sure that I didn't already upload a specific dataset or that a previous upload didn't fail.

**Comment by filippocastelli** [comment]
Also I have another problem that I can't seem to solve reliably about changing the allowed teams on a dataset from API.
should I open a separate github issue for that ? / Should it be under the ```webknossos``` repo instead of ```webknossos-libs```?

**Comment by jstriebel** [comment]
> Also I have another problem that I can't seem to solve reliably about changing the allowed teams on a dataset from API.

That's a great suggestion.

> should I open a separate github issue for that ? / Should it be under the webknossos repo instead of webknossos-libs?

Yes, that would be great. Here in the `webknossos-libs` repo is perfect. Thank's a lot for your feedback!
