### ISSUE TITLE
Add create_from_image_sequence

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-libs#632]
I think it would be cool to have an interface to the `cubing` tool of wkcuber from within the library.
It could look like:
```python
dataset = Dataset.create("/path/to/dataset", scale=(12,12,28))
layer = dataset.create_layer_from_image_sequence(
  ["/path/to/001.tiff", "/path/to/002.tiff", ...], 
  chunk_size=(32,32,32), 
  batch_size=16, 
  compress=True,
)
layer.downsample()

```

It is debatable whether this should be a function of `Mag`, `Layer` or `Dataset`.

**Comment by jstriebel** [comment]
Sounds good! I think this issue would be a great opportunity to clean up the related code. I'm not sure if we want to have all related packages as direct dependencies of the webknossos package as well, but we could define them as extras. This would need poetry dependency groups, which are not yet released, but come with the next minor release, see [the docs](https://python-poetry.org/docs/master/managing-dependencies/#dependency-groups). Also, we switch to extras at a later point and simply include them for now.

**Comment by jstriebel** [comment]
Defining extras is supported in poetry: https://python-poetry.org/docs/pyproject/#extras
