### ISSUE TITLE
Always use `spawn` in multiprocessing

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-libs#661]
I just debugged an issue where my multiprocessing worker would hang on Linux, but not on macOS. After 4 hours of debugging, I found out that `s3fs` seems to have issues with the `fork` start method in multiprocessing. See https://github.com/fsspec/s3fs/issues/464.

I know there have been other occasions where switching the start method was the solution. I wonder if there are any downsides to always use `spawn` (or `forkserver` where available) within the ProcessPoolExecutors from `cluster_tools`?

**Comment by jstriebel** [comment]
The only downside I know of is performance. If this starts to be a frequent problem, this seems useful, but we might also just change the start-method if necessary (automatically).
