### ISSUE TITLE
add_copy_layer results in FileExistsError for remote dataset layer

### ISSUE THREAD

**Issue by erjel** [scalableminds/webknossos-libs#781]
I would like to switch to remote datasets. Since I still have some annotations with fallback layers, I need to merge the downloaded annotation with a segmentation layer of a remote dataset. During this process I stumbled across an error while using `add_copy_layer`.

To illustrate the error I created a test case 'test_remote_dataset_add_copy_layer.py'':

```Python
from pathlib import Path

import webknossos as wk

def test_add_copy_layer(tmp_path: Path) -> None:

    url = "https://webknossos.org/datasets/scalable_minds/l4_sample_dev"
    
    output_path = tmp_path / 'out'

    output_dataset = wk.Dataset(output_path, voxel_size=(1,1,1))

    fallback_layer_name = 'color'

    fallback_layer = wk.Dataset.open_remote(url)\
                        .get_layer(fallback_layer_name)
    
    output_layer = output_dataset.add_copy_layer(
        fallback_layer, fallback_layer_name
    )
```
When I run the test case via
```
poetry run python -m pytest test_remote_dataset_add_copy_layer.py
```
I get the
<details>
  <summary>FileExistsError</summary>

```
tmp_path = PosixPath('/tmp/pytest-of-user/pytest-128/test_add_copy_layer0')

    def test_add_copy_layer(tmp_path: Path) -> None:

        url = "https://webknossos.org/datasets/scalable_minds/l4_sample_dev"

        output_path = tmp_path / 'out'

        output_dataset = wk.Dataset(output_path, voxel_size=(1,1,1))

        fallback_layer_name = 'color'

        fallback_layer = wk.Dataset.open_remote(url)\
                            .get_layer(fallback_layer_name)

>       output_layer = output_dataset.add_copy_layer(
            fallback_layer, fallback_layer_name
        )

test_remote_dataset_add_copy_layer.py:18:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
webknossos/dataset/dataset.py:1094: in add_copy_layer
    self._layers[layer_name] = self._initialize_layer_from_properties(
webknossos/dataset/dataset.py:1369: in _initialize_layer_from_properties
    return Layer(self, properties)
webknossos/dataset/layer.py:191: in __init__
    self.path.mkdir(parents=True, exist_ok=True)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = PosixPath('/tmp/pytest-of-user/pytest-128/test_remote_dataset_add_copy_layer/out/color'), mode = 511, parents = True, exist_ok = True

    def mkdir(self, mode=0o777, parents=False, exist_ok=False):
        """
        Create a new directory at this given path.
        """
        if self._closed:
            self._raise_closed()
        try:
>           self._accessor.mkdir(self, mode)
E           FileExistsError: [Errno 17] File exists: '/tmp/pytest-of-user/pytest-128/test_add_copy_layer0/out/color'

../../../python3.8/pathlib.py:1288: FileExistsError
```
</details>

Tested on 
- `master`
- `v0.10.10`
- `v0.10.5`

**Comment by jstriebel** [comment]
Hello @erjel,

Thank you for the precise bug-report :+1: I could re-produce the problem, and we are working on a solution.

In the meantime, you could use `wk.Dataset.open_remote(url).copy_dataset(output_path)`, if copying all layers is an option for you, or `wk.Dataset.download(url, path=output_path)`.

`add_copy_layer` is traversing the filesystem, which currently contains a bug that prohibits the traversal with remote datasets. The other two proposed methods do not have this problem.

**Comment by erjel** [comment]
Hi @jstriebel ,

thanks for the quick response! 👍 

I would like to avoid downloading the full dataset ... 

Another way to workaround this problem would be the downloading the annotations (or regions of it) with the fallback layer already applied.
It looks like you guys did some [work](https://github.com/scalableminds/webknossos/pull/6310) in this direction in the past and closed the associated [pull request](https://github.com/scalableminds/webknossos/issues/6270). Is it already functional/ is there documentation available? Without further help/ documentation I do not fully understand the line:

> request a bounding box that contains that segment, e.g. http://localhost:9000/tracings/volume/zarr/e1d6f00c-84ad-494c-9134-a9deefa4ecc7/1/0.2.4.1?token=secretSampleUserToken

as mentioned in another [pull request](https://github.com/scalableminds/webknossos/pull/6310)

**Comment by jstriebel** [comment]
@erjel As of `v0.10.14` `add_copy_layer` works now with remote datasets (PR #790). I double-checked this with your original code example which works now. I'll close this issue therefore, feel free to re-open it if some problems remain. Thanks again for the great report!
