### ISSUE TITLE
WK Python client: Allow Team Operations by Name Instead of ID

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos-libs#802]
## Detailed Description
Operations like setting allowed teams for datasets can currently only take team IDs. There is, however, no way for users to get this ID via the webKnossos UI. It would be great if the API could also do this by team name. The name is already unique per organization.

**Comment by normanrz** [comment]
```python

ds = wk.Dataset.open_remote("...")
ds.allowed_teams = [wk.Team.get_by_name("Default")]
```
