### ISSUE TITLE
Set folder for RemoteDataset

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-libs#832]
## Detailed Description
- Affected library: webknossos

webKnossos now supports dataset management in the form of folders. It would be great to be able to assign folders using the `RemoteDataset` class.

## Use Cases & Context
- Import scripts e.g. with PublishDataset in Voxelytics

**Comment by normanrz** [comment]
@fm3 is there already an API on the webKnossos side to support this. I think a good UX would be to have the user write the breadcrumb path, e.g. `folder=/strokevision/a/b`

**Comment by fm3** [comment]
The datasetUpdate call now accepts an optional `folderId` parameter in the body.

With `/folders/tree`, the client could fetch the full tree to map from a path using folder names to the id. (That route has no swagger annotations yet, though).

Note that we decided that names don’t have to be unique per layer, so a path of folder names may be ambiguous.

As an additional feature, the client could also (attempt to) create the folder path if it does not yet exist, using `POST /folders/create`. Compare https://github.com/scalableminds/webknossos/blob/master/conf/webknossos.latest.routes#L84
