### ISSUE TITLE
Adding a tree from one skeleton to another does not work

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos-libs#890]
```python
import webknossos as wk

import webknossos as wk

def main() -> None:
    skeleton_a = wk.Skeleton.load("./a.nml")
    skeleton_b = wk.Skeleton.load("./b.nml")

    for tree in skeleton_a.flattened_trees():
        skeleton_b.add_tree(tree)

    skeleton_b.save("./c.nml")

if __name__ == '__main__':
    main()

```

produces only an nml with empty trees (the `<thing>` elements are there, but nodes and edges are missing).

**Comment by hotzenklotz** [comment]
@philippotto The code example above will only add the tree the `skeleton_b` in the error case, i.e. when it was not found. So yes, the resulting new NML should be empty.

**Comment by philippotto** [comment]
The original logic of the code is to copy a tree from skeleton A to skeleton B if it's not present in B. So, in the end, B should contain all trees from A. The code even works with regard to copying the high level tree object, but the trees themselves are empty then (i.e., the nodes and edges are missing).

I simplified the code a bit, since the try-except wasn't really necessary to exemplify the bug.
