### ISSUE TITLE
Dataset.from_images does not take large compressed images, citing „decompression bomb DOS“

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos-libs#892]
Tried to convert jpg files, got `DecompressionBombError: Image size (352268961 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.`

Is there a way to raise that limit? 350 MP images are a valid use case.

Manually converting the images to tif first fixed the issue for me.

**Comment by fm3** [comment]
@normanrz This is included in https://github.com/scalableminds/voxelytics/pull/3258/files if I read that right? Would it be complicated to add it to the libs as well?

**Comment by normanrz** [comment]
No, but it is a global setting. I'm not sure if that would be a good idea in case people want to use the wklibs with other libs.
