### ISSUE TITLE
If annotations don't have enough slices...

### ISSUE THREAD

**Issue by azatian** [scalableminds/webknossos-libs#896]
Dear ScalableMinds,

I have been attempting to download my annotations as a segmentation mask from our server's WK instance. And I believe I have run into an issue that I can't solve. I think it's related to the underlying zarr file and how the chunk size is set up.

```
import webknossos as wk
dataset = wk.Dataset.open("our-zarr-link")
MAG = wk.Mag("1")
SEGMENT_IDS = [1]
mag_view = dataset.get_segmentation_layers()[0].get_mag(MAG)
the_zarr = mag_view.get_zarr_array()
the_zarr.info()
```

This is the output of the_zarr.info()

Type	zarr.core.Array
Data type	uint32
Shape	(1, 912, 912, 6)
Chunk shape	(1, 32, 32, 32)
Order	F
Read-only	False
Compressor	None
Store type	zarr.storage.FSStore
No. bytes	19961856 (19.0M)
No. bytes stored	161
Storage ratio	123986.7
Chunks initialized	0/841

Every time I try to do anything with mag_view including the functions read and get_buffered_slice_reader as well as any zarr array operations, even rechunking, I get the following error:

ValueError: cannot reshape array of size 0 into shape (1,32,32,32)

I tried to create a new mag with a smaller chunk size, one that fits with my data, and it seems like I can't add a mag on a layer that is hosted as a zarr link. I get this error.

ClientResponseError: 400, message='Bad Request', url=URL('our-zarr-link/Volume/2/.zarray')

pip show webknossos
Version: 0.10.24

**Comment by hotzenklotz** [comment]
Thanks for the bug report. Have you tried updating to the latest version of the webknossos lib `v0.12.3`? Your package is almost a year old.

I just tried your example from above and I have no trouble with `mag_view.read()` with the latest version, i.e.:
```
import webknossos as wk

dataset = wk.Dataset.open_remote(
        dataset_name_or_url="l4dense_motta_et_al_demo_v2",
        organization_id="scalable_minds",
    )

MAG = wk.Mag("1")
SEGMENT_IDS = [1]
mag_view = dataset.get_segmentation_layers()[0].get_mag(MAG)
the_zarr = mag_view.get_zarr_array()
the_zarr.info

data = mag_view.read(absolute_bounding_box=wk.BoundingBox((10, 10, 10), (10, 10,10))) 
data.shape

>>> (1, 10, 10, 10)
```

**Comment by hotzenklotz** [comment]
Mhm, I believe the error stems from the line:
```
dataset = wk.Dataset.open("http://catmaid2.hms.harvard.edu:9000/data/annotations/zarr/4pJXHDyVK_rvi7db") 
```

The webknossos-libs are meant to interface with WEBKNOSSOS URI for datasets and annotations, i.e. `https://<wkserver>.com/annotations/6124d30a010000ab009167ed` or `https://<wkserver>.com/datasets/scalable_minds/110629_k0725_segmentation_v1/view`. 

The libs do not support loading/streaming Zarr links. Please directly use a Zarr library such as [`zarr-python` ](https://github.com/zarr-developers/zarr-python) for that. Try 
```
import zarr

color_layer = zarr.open_group("http://catmaid2.hms.harvard.edu:9000/data/annotations/zarr/4pJXHDyVK_rvi7db")
color_layer.tree()

>> / <zarr.hierarchy.Group '/shape'> <zarr.hierarchy.Group '/dtype'>
 ├── .zgroup
 ├── Volume
 │   └── 1 (1, 912, 912, 6) uint32
 ├── cellseg
 │   └── 1 (1, 912, 912, 6) uint8
 ├── datasource-properties.json
 └── img
     └── 1 (1, 912, 912, 6) uint8

color_layer["/img/1"].shape
>> (1, 912, 912, 6)```

For compatibility and interoperability purposes with other tools WK can expose it's data as Zarr-API compatbile URIs through the UI (as you did) or by exposing the raw zarr-object through the libs for working `zarr-python` or `dask`.

**Comment by hotzenklotz** [comment]
Thanks for the detailed listing. For completeness sake, what version or release of WEBKNOSSOS are you running? 

You can find the version number in the "help" section of the navbar:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/1105056/232017674-5b34d057-fc09-4ed3-b5ab-5da840ed78d8.png">

**Comment by azatian** [comment]
Hello! We are using version 22.09.0
We currently have issues with the Python client finding our annotations as datasets, so that is why I decided to try the zarr link route. I can post about that issue as well, but didn't want to convolute too many issues together.

**Comment by hotzenklotz** [comment]
> We are using version 22.09.0

That version is more than half a year old. In this timeframe we have worked extensively with the Zarr community and improved the stability and compatibility of the Zarr APIs in WK. While I can not promise that an update will resolve your issue I am fairly confident that it might.

> We currently have issues with the Python client finding our annotations as datasets

Interesting. Let's hear it. (Feel free to open a second issues/thread for that). Generally speaking Annotations ≠ Datasets. A dataset typically contains the raw microscopy data, metadata, access permissions etc. An annotation typically contains a reference to the dataset and any new volume and skeleton labels/makers that you placed. A dataset can usually have several annotations "connected" to it, e.g. 10 users doing one annotation for the same dataset (1:n relationship). Unfortunately, in reality the border between the two concepts is sometime very "fluid" and perhaps the naming of our APIs needs to be clearer. Feedback is always welcome :-)

Hence, there are different webknossos-libs Python object for Annotations and Datasets. If you only interested in the volume annotation of the dataset (and assuming that the volume annotations were created from scratch on a "blank" surface), I recommend the follow code examples: 
- https://docs.webknossos.org/webknossos-py/examples/download_segments.html
- https://docs.webknossos.org/webknossos-py/examples/learned_segmenter.html
