### ISSUE TITLE
wk.Dataset.from_images sets bbox too large

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos-libs#961]
When using wk.Dataset.from_images sets bbox create a new dataset from images, the bounding box is set to be power-of-twos (probably due to the shard size), but it should be more precise than that.

Also see [slack discussion](https://scm.slack.com/archives/CBV2Q463E/p1698764237326869).

**Comment by markbader** [comment]
I can't reproduce this behavior anymore. As the logic for the calculation of the bounding box has changed, I think this issue can be closed for now.
